### ISSUE TITLE
Underscore in repo name causes form validation error

### ISSUE THREAD

**Issue by jforaker** [ory-am/gitdeploy#19]
Repo names should be able to contain underscores

**Comment by arekkas** [comment]
Thanks for the report. :)

You can bypass validation by requesting: https://www.gitdeploy.io/deploy?repository={{url_encoded_repository_url}}

e.g.: `https%3A%2F%2Fgithub.com%2Farekkas%2Ffoobar.git`

Note to self:
Fix [https://github.com/ory-am/gitdeploy/blob/master/app/app/scripts/controllers/landing.js#L33](here). Backend already supports [https://github.com/ory-am/gitdeploy/blob/master/main.go#L49](underscores )

@inyono could you add this to the react refactor as well?

**Comment by jforaker** [comment]
Re: your note to self.. I think it might be the angular validator on the input itself 

```
<input required="" pattern="(http|https)\:\/\/github\.com\/[a-zA-Z0-9\-]+\/[a-zA-Z0-9\-\.]+\.git" 
ng-model="repository.url" aria-describedby="helpBlock" type="text" length="30" class="form-control input-lg ng-invalid ng-touched ng-dirty ng-valid-parse ng-valid-required ng-invalid-pattern" id="repositoryUrl" placeholder="https://github.com/your/repository.git">
```

**Comment by arekkas** [comment]
Ah right, thanks :) I'll fix it later today

**Comment by arekkas** [comment]
It's fixed but not live yet. We have to wait for some PRs to land at http://flynn.io before we can deploy :)
